services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    labels:
      com.github.nginx-proxy.nginx: 'true'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx_logs:/var/log/nginx
    networks:
      - odoo-net
    restart: always

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${LE_EMAIL}
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - odoo-net
    restart: always

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - odoo-net
    restart: always

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      # - DATABASE=odoo
      - VIRTUAL_HOST=${CLIENT_DOMAIN}
      - LETSENCRYPT_HOST=${CLIENT_DOMAIN}
      - LETSENCRYPT_EMAIL=${LE_EMAIL}
      - VIRTUAL_PORT=8069
      - PGUSER=odoo
      - PGPASSWORD=odoo
      - PGHOST=db
      - PGPORT=5432
      # - PGDATABASE=odoo
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/custom-addons:/mnt/extra-addons
      - ./odoo/enterprise:/mnt/enterprise-addons
    expose:
      - "8069"
    networks:
      - odoo-net
    restart: always

networks:
  odoo-net:
    driver: bridge
